project:
  type: website
  title: "Unfold.jl Workshop 2025"

website:
  title: "Unfold.jl Workshop 2025"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - about.qmd
    background: primary

format:
  html:
    theme: minty
    css: styles.css
    toc: true